defaults: &defaults
  working_directory: ~/badweather
  docker:
    - image: gradyrogers/circleci2-aws


version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            chmod +x deploy.sh
            ./deploy.sh


  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: yarn files:prod && yarn build:prod && yarn style

workflows:
  version: 2


  deploy_production:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

  general:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

