defaults: &defaults
  working_directory: ~/badweather
  docker:
    - image: gradyrogers/circleci2-aws


version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Get env
          command: |
            aws s3 cp s3://rogersops/badweatherfront/master/prod.env ./ \
            --region us-east-1 \
            --access-key-id $AWS_ACCESS_KEY_ID \
            --secret-access-key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy
          command: |
            yarn build:prod
            mv dist/index.js dist/index.$CIRCLE_BUILD_NUM.js
            mv dist/style.css dist/style.$CIRCLE_BUILD_NUM.css
            sed "s/BUILD_NUMBER/$CIRCLE_BUILD_NUM/g" ./dist/index.html
            aws s3 cp dist s3://badweatherfront --exclude "index.html" --recursive --acl public-read \
            --storage-class STANDARD --metadata-directive REPLACE \
            --cache-control max-age=31536000 \
            --region us-east-1 \
            --access-key-id $AWS_ACCESS_KEY_ID \
            --secret-access-key $AWS_SECRET_ACCESS_KEY
            aws s3 cp dist/index.html s3://badweatherfront/ --acl public-read \
            --storage-class STANDARD --metadata-directive REPLACE \
            --cache-control max-age=300 \
            --region us-east-1 \
            --access-key-id $AWS_ACCESS_KEY_ID \
            --secret-access-key $AWS_SECRET_ACCESS_KEY


workflows:
  version: 2


  deploy_production:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

