defaults: &defaults
  working_directory: ~/badweather
  docker:
    - image: gradyrogers/circleci2-aws


version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn
      - run:
          name: Copy Files
          command: yarn files
      - run:
          name: Build JS
          command: yarn build:prod
      - run:
          name: Styles
          command: yarn style
      - run:
          name: mark build version
          command: |
            mv dist/index.js dist/index.$CIRCLE_BUILD_NUM.js
            mv dist/style.css dist/style.$CIRCLE_BUILD_NUM.css
            sed -i "s/BUILD_NUMBER/$CIRCLE_BUILD_NUM/g" dist/index.html
            cat dist/index.html
      - run:
          name: Deploy
          command: |
            aws s3 cp dist s3://badweatherfront --exclude "index.html" --recursive --acl public-read \
            --storage-class REDUCED_REDUNDANCY --metadata-directive REPLACE \
            --cache-control max-age=31536000
            aws s3 cp dist/index.html s3://badweatherfron/ --acl public-read \
            --storage-class REDUCED_REDUNDANCY --metadata-directive REPLACE \
            --cache-control max-age=300


workflows:
  version: 2


  deploy_production:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

