defaults: &defaults
  working_directory: ~/badweather
  docker:
    - image: gradyrogers/circleci2-aws


version: 2
jobs:

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Get env
          command: |
            aws s3 cp s3://rogersops/badweatherfront/master/prod.env ./ \
            --region us-east-1
      - run:
          name: Deploy
          command: |
            chmod +x deploy.sh
            ./deploy.sh


workflows:
  version: 2


  deploy_production:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

